github:
  repository_url: https://github.com/palliate/palliate

remote_theme: just-the-docs/just-the-docs

aux_links:
  '<button type="button" name="button" class="btn btn-green">Palliate on Github</button>':
    - "//github.com/palliate/palliate"

logo: "logo.svg"